services:
  mysql-server:
    image: mysql:8.0
    container_name: zabbix-db
    restart: unless-stopped
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-7.0-latest
    container_name: zabbix-server
    restart: unless-stopped
    env_file: .env
    environment:
      DB_SERVER_HOST: mysql-server
    depends_on:
      - mysql-server
    ports:
      - "10051:10051"

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-7.0-latest
    container_name: zabbix-web
    restart: unless-stopped
    env_file: .env
    environment:
      DB_SERVER_HOST: mysql-server
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: America/Halifax
    depends_on:
      - mysql-server
      - zabbix-server
    ports:
      - "80:8080"

  zabbix-agent:
    image: zabbix/zabbix-agent2:alpine-7.0-latest
    container_name: zabbix-agent
    restart: unless-stopped
    environment:
      ZBX_HOSTNAME: "Zabbix server"
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - zabbix-server

volumes:
  db_data:
